---
title: "ALCA 2015"
author: "jcb"
date: "1 mai 2016"
output: html_document
---

Cartes IGN 2015
===============

Les cartes IGN 2015 intègrent les nouvelles régions. La colonne REG_NOM 2015 est différente de la colonne REG_NOM 2014. 

```{r}
require("rgdal") # requires sp, will use proj.4 if installed
require("maptools")

# Version macbook
path <- "/Users/jcb/Documents/R/GEOFLA_2-1_COMMUNE_SHP_LAMB93_FXX_2015-12-01/GEOFLA/1_DONNEES_LIVRAISON_2015/GEOFLA_2-1_SHP_LAMB93_FR-ED152/COMMUNE"

file <-"COMMUNE"
france <- readOGR(dsn = path, layer = file, encoding = "latin1") # règle le pb de accents
d.france <- france@data

par(mar = rep(0,4)) # on fait de la place
```

Création d'une colonne Ancienne Régions
---------------------------------------
```{r}
france@data$ANC_REG <- ""
france@data$ANC_REG[d.france$CODE_DEPT %in% c('08', 10, 51, 52)] <- "CHAMPAGNE-ARDENNE"
france@data$ANC_REG[d.france$CODE_DEPT %in% c(55, 57, 54, 88)] <- "LORRAINE"
france@data$ANC_REG[d.france$CODE_DEPT %in% c(67:68)] <- "ALSACE"
```

Exemple de la Lorraine
```{r}
lorraine <-  france[france$ANC_REG == "LORRAINE",]
plot(lorraine)

```

Uniquement les contours des départements
```{r}
region.lor1 <- unionSpatialPolygons(lorraine, IDs = lorraine@data$CODE_DEPT)
plot(region.lor1)
```

Uniquement le contour de la région 
```{r}
region.lor2 <- unionSpatialPolygons(lorraine, IDs = lorraine@data$CODE_REG)
plot(region.lor2)
```

Pour ajouter les coordonnées,il faut rajouter les marges basse et gauche, puis utiliser la fonction __axis()__
```{r}
par(mar = c(2,2,0,0))
plot(region.lor2)
axis(1)
axis(2)

```

Cartographie Alca
=================

Par communes:
```{r}
alca <-  france[france$ANC_REG %in% c("ALSACE", "CHAMPAGNE-ARDENNE", "LORRAINE"),]
plot(alca)
save(alca, file = "alca.Rda")

```

Uniquement le contour de la région 
```{r}
alca2 <- unionSpatialPolygons(alca, IDs = alca@data$CODE_REG)
plot(alca2)
save(alca2, file = "alca2.Rda")
```

Avec les limites des anciennes régions
```{r}
alca3 <- unionSpatialPolygons(alca, IDs = alca@data$ANC_REG)
plot(alca3)
save(alca3, file = "alca3.Rda")
```
projection des SU
-----------------
```{r}
library(rgdal)
library(sp)
load("~/Documents/CARTOGRAPHIE/CartographieR/RCarto/ALCA_2015/su_alca.Rda") #d hoptaux ALCA

spdfr <- d

## transformation en SpatialPointDataFrame
coordinates(spdfr) <- ~ Longitude + Latitude

## on déclare le système de coordonnées de référence: dégrés décimaux WGS84
proj4string(spdfr) <- CRS("+proj=longlat +ellps=WGS84")
spdfr

## conversion en Lambert étendu
spdfrLambert <- spTransform(spdfr, CRS("+init=epsg:27572"))
spdfrLambert

# conversion en Lambert93 à partir du système de projection de __alca3__:
spdfrLambert <- spTransform(spdfr, proj4string(alca3))

# fond de carte + hôpitaux
plot(alca3, axes = TRUE)
plot(spdfrLambert, add = T, pch = 16, col = "red")

# on peut récupérer les coordonnées de chaque point avec la fonction coordinates()
head(coordinates(spdfrLambert))
```
   Longitude Latitude
2  1050113.2  6841326
3  1050879.3  6840027

Ajouter Robert Pax:
```
text(coordinates(spdfrLambert[61,]), "Sarreguemines", col = "blue", cex = 0,6, pos = 4, offset = 0.2)

```

